// Code generated by "stringer -type=Gender"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Male-0]
	_ = x[Female-1]
	_ = x[Transgender-2]
	_ = x[PreferNotToSay-3]
}

const _Gender_name = "MaleFemaleTransgenderPreferNotToSay"

var _Gender_index = [...]uint8{0, 4, 10, 21, 35}

func (i Gender) String() string {
	if i < 0 || i >= Gender(len(_Gender_index)-1) {
		return "Gender(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gender_name[_Gender_index[i]:_Gender_index[i+1]]
}
